### ISSUE TITLE
Weekly Tech Report #3

### ISSUE THREAD

**Issue by rainyear** [rainyear/lolita#12]
#### TODO
- [x] [Approach: Building a toy template engine in Python](http://alexmic.net/building-a-template-engine/) | [[翻译] 用Python做一个模板引擎玩具](http://www.ituring.com.cn/article/201361)
- [x] [Golang 交叉编译](http://blog.wizjin.com/2014/06/23/golang-cross-complie/)
- [x] [pip install 加速](http://topmanopensource.iteye.com/blog/2004853)
##### 1. [怎样写一个模板引擎](http://blog.rainy.im/2015/07/29/how-to-write-a-template-engine/)

Web开发中很难不用到模板引擎，不管是PHP、Django、RoR等后端开发框架，甚至很早之前在前端动态加载时遇到需要Js做模板引擎的情况。PHP的模板引擎我研究过一段时间用C语言写的扩展Blitz，后来只在那个项目的基础上加了一个`foreach`的[特性](https://github.com/rainyear/Blitz-featured)；Js前端的应用以前搜到jQuery作者写的一个非常精简版本的[Js微型模板引擎](http://ejohn.org/blog/javascript-micro-templating/)，一直想研究一下，最近又看到这篇Python写的模板引擎玩具（虽然已经是13年的文章），因此写了一篇[怎样写一个模板引擎](http://blog.rainy.im/2015/07/29/how-to-write-a-template-engine/)进行总结整理。
##### 2. Go 语言的跨平台发布

Go语言的优势之一就是方便的跨平台编译、执行，比如在Mac中的开发环境，如果生产环境为Linux，我之前采用[Godeps](https://github.com/rainyear/lolita/issues/6)进行部署，但由于一些依赖包的安装可能需要翻墙等因素，并不是很方便；如果编译成生产环境下可以直接执行的二进制就方便很多。

首先需要按照目标环境变异Go语言源码：

``` sh
$ cd /usr/local/go/src
$ CGO_ENABLED=0 GOOS=linux GOARCH=amd64 ./make.bash
$ CGO_ENABLED=0 GOOS=windows GOARCH=amd64 ./make.bash
```

然后在项目目录下编译到指定系统：

``` sh
$ CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build 
$ CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build
```

遇到的一个问题是后续安装go语言包的时候可能报错：

```
go install runtime/cgo: open /usr/local/go/pkg/darwin_amd64/runtime/cgo.a: permission denied
```

具体可以参考[Github issues](https://github.com/AlekSi/nut/issues/26)，暂时的解决方案是：

``` sh
export CGO_ENABLED=0
go get ...
```
##### 3. pip install 加速

`pip install` 是非常常用的安装Python第三方包的方法，以前也发现时快时慢，最近经常出现`time out`的情况，就想找一下有没有国内的镜像。国内镜像还真不少：
1. [阿里云：`http://mirrors.aliyun.com/pypi/simple/`](http://mirrors.aliyun.com/help/pypi)
2. [豆瓣：`http://pypi.douban.com/simple`](http://pypi.douban.com/simple)
3. [V2EX：`http://pypi.v2ex.com/simple`](http://pypi.v2ex.com/simple)

用法有两种：

``` sh
#1. 当前安装使用指定镜像
pip install -i http://<mirror>/simple <package>

#2. 全局设定
# 添加文件 ~/.pip/pip.conf
[global]
index-url = http://<mirror>/simple
```
