### ISSUE TITLE
Weekly Tech Report #4

### ISSUE THREAD

**Issue by rainyear** [rainyear/lolita#13]
#### TODO
- [X] [理解Go 1.5 vendor](http://tonybai.com/2015/07/31/understand-go15-vendor/) | [Go 1.5中值得关注的几个变化](http://tonybai.com/2015/07/10/some-changes-in-go-1-5/)
- [X] [生成伪随机数](http://blog.rainy.im/2015/08/21/lcg-random-number-generator/)
- [X] [机器学习与计算机视觉](http://v.coodict.com/)
##### 1. Go 更新1.5

Go 发布第6个本定版本 Go1.5，安全起见还是先用上版本管理器[gvm](https://github.com/moovweb/gvm)。

``` bash
gvm install go1.5
```

之前没有用过 gvm 可能需要预先安装go1.4，并设定`GOROOT_BOOTSTRAP`：

``` bash
gvm install go1.4

GOROOT_BOOTSTRAP=~/.gvm/gos/go1.4.2 gvm install go1.5
```

安装没有报错的话可以查看当前安装的所有版本：

``` bash
gvm list

gvm gos (installed)

=> go1.4
   go1.5
   system
```
##### 2. 线性同余法生成伪随机数

SICP 中遇到的问题，使用的Scheme实现没有内置的random功能，顺便了解了一下计算机伪随机数生成原理并实现简单的线性同余产生器。
##### 3. 机器学习与计算机视觉站点

免费领取了两年的阿里云的虚拟晕主机，放了一个WordPress上去，主要收集、整理与机器学习（ML）、计算机视觉（CV）等相关的技术、文章、新闻等咨询信息。
