### ISSUE TITLE
Weekly Tech Report #1

### ISSUE THREAD

**Issue by rainyear** [rainyear/lolita#9]
#### About

每天都会关注一些技术论坛或新闻的分享([My Bookmarks](https://www.google.com/stars/vh754g3l3tqja/profile/folio/ssf_60fdea5e5d0120f8?hl=zh-CN))，但是大部分都会一看而过，没留下什么痕迹。于是决定每周做一下总结，对比较完整的项目、文章做一下总结与笔记，对一些新的知识点或有趣的技术、项目做一下记录。
#### TODO
- [ ] [Git from the inside out](https://codewords.recurse.com/issues/two/git-from-the-inside-out)
- [X] [Inceptionism: Going Deeper into Neural Networks](http://googleresearch.blogspot.ch/2015/06/inceptionism-going-deeper-into-neural.html) | [Caffe | Deep Learning Framework](http://caffe.berkeleyvision.org/)
- [X] [IPython notebook](http://ipython.org/notebook.html) & [Jupyter Project](https://jupyter.org/)

##### 1. Git from the inside out

图解 Git 工作流程中其内部是如何记录项目文件变化的，这篇还没时间看完，后续研究完再补上。他们这边的文章都写得不错：[recurse blog](https://codewords.recurse.com/issues/)，值得一读。
##### 2. Deepdream

人工神经网络是一种很重要的机器学习的方法，尤其是随着最近深度学习的兴起，又重新获得大众的关注。但是深度学习或人工神经网络都是基于很简单的数学模型 - 感知器（perceptron），相当于人类大脑中的神经元，而复杂的神经网络则是由许多不同的神经元（感知器）按照不同的层次组合得到的：

![deepdream](https://cloud.githubusercontent.com/assets/3953966/8636766/5c981910-28a5-11e5-98e1-e4ac6898478a.png)

虽然人工神经网络在图像识别等领域取得了显著的成绩，但是对于不同的神经网络层次（layer）之间，信息是如何传递的对于我们来说还是未知的。参照人类大脑的工作原理，可能较低层神经网络负责处理较低层的物理属性，如颜色、边界、朝向等特征的提取，较高层的神经网络负责物处理体类别、物体之间关系以及语义信息等。

Deepdream 这个项目就是将神经网络进行图像分类的中间过程所生成、传播的图像展示出来，意外地得到了具有魔幻色彩的“梦境图像”。 我做了一下实践，见 #10。除此之外，认识了 [Caffe](http://caffe.berkeleyvision.org) 框架，后面做神经网络模型或深度学习的时候应该可以用上，非常值得学习。

另外，由于 Deepdream 是用 ipython notebook 记录的，之前有了解过，虽然也一直在用 ipython，但是还没有用过 notebook，刚好借这个机会使用了一下，结果一下就爱上了它，下面就详细介绍一下。
##### 3. [IPython notebook](http://ipython.org/notebook.html) & [Jupyter Project](https://jupyter.org/)

ipython 就不用说了，就是一个增强版的Python解释器，一直在用它是因为它的Tab补全功能。这次用了一下notebook，发现它跟我在处理实验数据时用到的 [R Markdown](http://blog.rainy.im/2015/05/16/rmarkdown-in-rstudio/) 有异曲同工之妙，可以在一边做文档记录的同时，插入可执行的代码，最后可以直接导出带有执行结果的报告文档，可用于结果报告、笔记、教程课件等，非常方便。ipython notebook更让人惊艳的是[Jupyter Project](https://jupyter.org/)，也就是说你不仅可以在notebook 中插入Python代码，同时也支持其它语言，例如我装了一个Scheme的kernel，就可以创建Scheme版本的notebook：

<img width="262" alt="qq20150712-1 2x" src="https://cloud.githubusercontent.com/assets/3953966/8636840/da673dbe-28a8-11e5-9d1d-eb4a14312d1e.png">

更棒的是，Github已经支持ipython notebook文件格式，也就是说可以像Markdown一样直接展示出来[see: test_jupyter.ipynb](https://github.com/rainyear/lolita/blob/master/playground/test_jupyter.ipynb)！

用起来也很方便，我在Python3的virtualenv环境下安装的步骤如下：

``` sh
mkdir notes && cd notes
python3 -m venv venv3 # Python3 已经内置了venv模块，不再需要安装virtualenv

source venv3/bin/active
pip install "ipython[all]"

deactive && source venv3/bin/active # 有可能需要重新载入虚拟环境
ipython notebook
```

然后会跳到浏览器的`http://localhost:8888/`，如果需要其它语言，可以到[IPython-kernels-for-other-languages](https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages)找到。
#### MEMO
- [X] [命令行的艺术](https://github.com/jlevy/the-art-of-command-line/blob/master/README-zh.md)
- 很不错的总结，几个没用过但感觉很有用的命令：

``` sh
# 打印环境变量
printenv 

#用 pbcopy 复制任何命令的输出到桌面应用，用 pbpaste 粘贴输入。
pbcopy
pbpaste
```
- [pandoc](http://pandoc.org/): ipython notebook & Rmd 都用到；
